# Generated by Django 2.2.13 on 2021-09-08 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heypixel', '0009_auto_20210908_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_author',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
