# Generated by Django 2.2.13 on 2021-09-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heypixel', '0011_auto_20210909_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
